kind: pipeline
name: paggi-sdk-elixir-ecommerce

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
- name: clone
  image: docker:git
  when:
    ref:
    - refs/heads/development
    - refs/tags/v*
    event:
    - push
    - tag
  commands:
  - git clone $DRONE_REPO_LINK /drone/src
  - cd /drone/src
  - git checkout $DRONE_COMMIT

- name: before_script
  pull: default
  image: elixir:1.8-alpine
  when:
    ref:
    - refs/heads/development
    - refs/tags/v*
    event:
    - push
    - tag
  volumes:
  - name: mix
    path: /root/.mix
  commands:
  - apk --update add git openssh-client bash alpine-sdk coreutils curl
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

- name: test
  pull: default
  image: elixir:1.8-alpine
  environment:
    MIX_ENV: test
    PAGGI_ENVIRONMENT: staging
    PAGGI_TOKEN:
      from_secret: paggi_token
    PAGGI_VERSION: v1
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  when:
    ref:
    - refs/heads/development
    - refs/tags/v*
    event:
    - push
    - tag
  volumes:
  - name: mix
    path: /root/.mix
  commands:
  - apk --update add git openssh-client bash alpine-sdk coreutils curl
  - mix test

volumes:
- name: mix
  temp: {}